admin_page:
    pattern:  /
    defaults: { _controller: "SilverkixCMSBundle:AdminPage:index" }

admin_page_new:
    pattern:  /new
    defaults: { _controller: "SilverkixCMSBundle:AdminPage:new" }

admin_page_create:
    pattern:  /create
    defaults: { _controller: "SilverkixCMSBundle:AdminPage:create" }
    requirements: { _method: post }

admin_page_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SilverkixCMSBundle:AdminPage:edit" }

admin_page_update:
    pattern:  /{id}/update
    defaults: { _controller: "SilverkixCMSBundle:AdminPage:update" }
    requirements: { _method: post|put }

admin_page_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SilverkixCMSBundle:AdminPage:delete" }
    requirements: { _method: post|delete }
