## login paths outside firewall
admin_login:
    pattern:   /login
    defaults:  { _controller: SilverkixCMSBundle:Admin:login }

admin_login_check:
    pattern:   /login_check

admin_logout:
    path:   /logout

## Public website paths
home:
    pattern:  /
    defaults: { _controller: SilverkixCMSBundle:Default:index }
